question_data =[
{"type": "boolean", 
 "difficulty": "easy", 
 "category": "Entertainment: Video Games",
 "question": "There are 6 legendary cards in Clash Royale.",
 "correct_answer": "False", 
 "incorrect_answers": ["True"]},

{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
 "question": "Snakes and Ladders was originally created in India?",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
 "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "Tetris is the #1 best-selling video game of all-time.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
 "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The main antagonist in the videogame Saints Row IV is an entity known as The Mastermind.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy",
 "category": "Entertainment: Cartoon &amp; Animations",
 "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "History",
 "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "Tokyo is the capital of Japan.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Animals",
 "question": "Rabbits are rodents.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
 "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "Toronto is the capital city of the North American country of Canada.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Vehicles",
 "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
 "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
 "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "There are no deserts in Europe.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
 "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
 "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Politics",
 "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
 "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "Activision created Battlefield 1.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "History",
 "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
 "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
 "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy",
 "category": "Entertainment: Japanese Anime &amp; Manga",
 "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Animals",
 "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
 "question": "George Lucas directed the entire original Star Wars trilogy.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "History",
 "question": "Kublai Khan is the grandchild of Genghis Khan?",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "History",
 "question": "The Spitfire originated from a racing plane.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Animals",
 "question": "A flock of crows is known as a homicide.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
 "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
 "question": "The book 1984 was published in 1949.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Mythology",
 "question": "A wyvern is the same as a dragon.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "Greenland is covered with grass and Iceland covered with ice.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Geography",
 "question": "St. Louis is the capital of the US State Missouri.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Celebrities",
 "question": "Marilyn Monroe was born on July 1, 1926.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "easy",
 "category": "Entertainment: Japanese Anime &amp; Manga",
 "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
 "question": "John Williams composed the music for &quot;Star Wars&quot;.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
 "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
 "correct_answer": "False", "incorrect_answers": ["True"]}]
